from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/mock-api', methods=['GET'])
def mock_api():
    response = {
        "result": True,
        "message": {
            "fields": [
                {"fieldName": "Id", "fieldType": 3, "fieldMask": "", "fieldLength": 2, "fieldDecimals": 0},
                {"fieldName": "Matricula", "fieldType": 9, "fieldMask": "", "fieldLength": 9, "fieldDecimals": 0},
                {"fieldName": "Colaborador", "fieldType": 9, "fieldMask": "", "fieldLength": 16, "fieldDecimals": 0},
                {"fieldName": "Nome", "fieldType": 9, "fieldMask": "", "fieldLength": 4, "fieldDecimals": 0},
                {"fieldName": "Nome_Completo", "fieldType": 9, "fieldMask": "", "fieldLength": 13, "fieldDecimals": 0},
                {"fieldName": "Celular_corporativo", "fieldType": 9, "fieldMask": "", "fieldLength": 19, "fieldDecimals": 0},
                {"fieldName": "Data_admissao", "fieldType": 9, "fieldMask": "", "fieldLength": 13, "fieldDecimals": 0},
                {"fieldName": "Tipo_def", "fieldType": 3, "fieldMask": "", "fieldLength": 16, "fieldDecimals": 0},
                {"fieldName": "Nacionalidade_id", "fieldType": 3, "fieldMask": "", "fieldLength": 16, "fieldDecimals": 0},
                {"fieldName": "Nacionalidade", "fieldType": 9, "fieldMask": "", "fieldLength": 13, "fieldDecimals": 0},
                {"fieldName": "Sexo", "fieldType": 9, "fieldMask": "", "fieldLength": 4, "fieldDecimals": 0},
                {"fieldName": "Sexo_id", "fieldType": 3, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Data_rescisao", "fieldType": 9, "fieldMask": "", "fieldLength": 13, "fieldDecimals": 0},
                {"fieldName": "Usuario", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Usuario_completo", "fieldType": 9, "fieldMask": "", "fieldLength": 16, "fieldDecimals": 0},
                {"fieldName": "Email", "fieldType": 9, "fieldMask": "", "fieldLength": 5, "fieldDecimals": 0},
                {"fieldName": "Cpf", "fieldType": 9, "fieldMask": "", "fieldLength": 3, "fieldDecimals": 0},
                {"fieldName": "Cpf_num", "fieldType": 9, "fieldMask": "", "fieldLength": 10, "fieldDecimals": 0},
                {"fieldName": "Rg", "fieldType": 9, "fieldMask": "", "fieldLength": 2, "fieldDecimals": 0},
                {"fieldName": "Orgaoemissor_rg", "fieldType": 9, "fieldMask": "", "fieldLength": 15, "fieldDecimals": 0},
                {"fieldName": "Estadoemissor_rg", "fieldType": 9, "fieldMask": "", "fieldLength": 16, "fieldDecimals": 0},
                {"fieldName": "Dtaemissao_rg", "fieldType": 9, "fieldMask": "", "fieldLength": 13, "fieldDecimals": 0},
                {"fieldName": "Hierarquia_ua", "fieldType": 9, "fieldMask": "", "fieldLength": 13, "fieldDecimals": 0},
                {"fieldName": "Hierarquia_id", "fieldType": 3, "fieldMask": "", "fieldLength": 13, "fieldDecimals": 0},
                {"fieldName": "Hierarquia", "fieldType": 9, "fieldMask": "", "fieldLength": 10, "fieldDecimals": 0},
                {"fieldName": "Matricula_L", "fieldType": 8, "fieldMask": "", "fieldLength": 15, "fieldDecimals": 2},
                {"fieldName": "Situacao", "fieldType": 9, "fieldMask": "", "fieldLength": 8, "fieldDecimals": 0},
                {"fieldName": "Situacao_id", "fieldType": 3, "fieldMask": "", "fieldLength": 11, "fieldDecimals": 0},
                {"fieldName": "Vinculo", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Vinculo_id", "fieldType": 3, "fieldMask": "", "fieldLength": 10, "fieldDecimals": 0},
                {"fieldName": "Folha", "fieldType": 9, "fieldMask": "", "fieldLength": 5, "fieldDecimals": 0},
                {"fieldName": "Folha_id", "fieldType": 3, "fieldMask": "", "fieldLength": 8, "fieldDecimals": 0},
                {"fieldName": "Vinculo_2", "fieldType": 9, "fieldMask": "", "fieldLength": 10, "fieldDecimals": 0},
                {"fieldName": "Cargo", "fieldType": 9, "fieldMask": "", "fieldLength": 5, "fieldDecimals": 0},
                {"fieldName": "Cargo_sem_estagio", "fieldType": 9, "fieldMask": "", "fieldLength": 17, "fieldDecimals": 0},
                {"fieldName": "Cargo_id", "fieldType": 3, "fieldMask": "", "fieldLength": 8, "fieldDecimals": 0},
                {"fieldName": "Cargo_id_ga", "fieldType": 3, "fieldMask": "", "fieldLength": 11, "fieldDecimals": 0},
                {"fieldName": "Considerar Desativado", "fieldType": 12, "fieldMask": "Yes,No", "fieldLength": 1, "fieldDecimals": 0},
                {"fieldName": "Funcao", "fieldType": 9, "fieldMask": "", "fieldLength": 6, "fieldDecimals": 0},
                {"fieldName": "Funcao_id", "fieldType": 9, "fieldMask": "", "fieldLength": 9, "fieldDecimals": 0},
                {"fieldName": "Funcao_e1_id", "fieldType": 9, "fieldMask": "", "fieldLength": 12, "fieldDecimals": 0},
                {"fieldName": "Predio", "fieldType": 9, "fieldMask": "", "fieldLength": 6, "fieldDecimals": 0},
                {"fieldName": "Sala", "fieldType": 9, "fieldMask": "", "fieldLength": 4, "fieldDecimals": 0},
                {"fieldName": "Ramal", "fieldType": 9, "fieldMask": "", "fieldLength": 5, "fieldDecimals": 0},
                {"fieldName": "Data_nascimento", "fieldType": 9, "fieldMask": "", "fieldLength": 15, "fieldDecimals": 0},
                {"fieldName": "Qtdhorasmes", "fieldType": 8, "fieldMask": "", "fieldLength": 11, "fieldDecimals": 2},
                {"fieldName": "End_tipo_logradouro", "fieldType": 9, "fieldMask": "", "fieldLength": 19, "fieldDecimals": 0},
                {"fieldName": "End_logradouro", "fieldType": 9, "fieldMask": "", "fieldLength": 14, "fieldDecimals": 0},
                {"fieldName": "End_numero", "fieldType": 9, "fieldMask": "", "fieldLength": 10, "fieldDecimals": 0},
                {"fieldName": "End_complemento", "fieldType": 9, "fieldMask": "", "fieldLength": 15, "fieldDecimals": 0},
                {"fieldName": "End_cep", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "End_bairro", "fieldType": 9, "fieldMask": "", "fieldLength": 10, "fieldDecimals": 0},
                {"fieldName": "End_municipio", "fieldType": 9, "fieldMask": "", "fieldLength": 14, "fieldDecimals": 0},
                {"fieldName": "End_estado", "fieldType": 9, "fieldMask": "", "fieldLength": 10, "fieldDecimals": 0},
                {"fieldName": "Ddd_Res", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Tel_Res", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Ddd_Cel", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Tel_Cel", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Banco_Agencia", "fieldType": 9, "fieldMask": "", "fieldLength": 12, "fieldDecimals": 0},
                {"fieldName": "Conta", "fieldType": 9, "fieldMask": "", "fieldLength": 5, "fieldDecimals": 0},
                {"fieldName": "Conta_Dig", "fieldType": 9, "fieldMask": "", "fieldLength": 9, "fieldDecimals": 0},
                {"fieldName": "Banco_reembolso", "fieldType": 9, "fieldMask": "", "fieldLength": 15, "fieldDecimals": 0},
                {"fieldName": "Agencia_reembolso", "fieldType": 9, "fieldMask": "", "fieldLength": 17, "fieldDecimals": 0},
                {"fieldName": "Agencia_Dig_Reembolso", "fieldType": 9, "fieldMask": "", "fieldLength": 24, "fieldDecimals": 0},
                {"fieldName": "Conta_Reembolso", "fieldType": 9, "fieldMask": "", "fieldLength": 15, "fieldDecimals": 0},
                {"fieldName": "Conta_Dig_Reembolso", "fieldType": 9, "fieldMask": "", "fieldLength": 19, "fieldDecimals": 0},
                {"fieldName": "Sigla_Diretoria", "fieldType": 9, "fieldMask": "", "fieldLength": 15, "fieldDecimals": 0},
                {"fieldName": "Estagio", "fieldType": 9, "fieldMask": "", "fieldLength": 16, "fieldDecimals": 0},
                {"fieldName": "Inativo", "fieldType": 9, "fieldMask": "", "fieldLength": 7, "fieldDecimals": 0},
                {"fieldName": "Grau_instrucao", "fieldType": 9, "fieldMask": "", "fieldLength": 14, "fieldDecimals": 0},
          
            ],   
            "values": [
                {
                    "recNo": 0,
                    "record": [
                        {"value": "123345"},
                        {"value": "00012345"},
                        {"value": "S"},
                        {"value": "Jose"},
                        {"value": "Jose Silva"},
                        {"value": "(84)991497655"},
                        {"value": "01/02/1972"},
                        {"value": "0"},
                        {"value": "10"},
                        {"value": "Brasileira"},
                        {"value": "1"},
                        {"value": "Masculino"},
                        {"value": ""},
                        {"value": "jsilva"},
                        {"value": "jsilva"},
                        {"value": "joao.silva@teste.com"},
                        {"value": "119.876.543-21"},
                        {"value": "11987654321"},
                        {"value": "383020"},
                        {"value": "SSP"},
                        {"value": "DF"},
                        {"value": "16/05/1987"},
                        {"value": "2220"},
                        {"value": "3536"},
                        {"value": "001.000.031.001.000.000.001"},
                        {"value": "51401"},
                        {"value": "EM ATIVIDADE NORMAL"},
                        {"value": "1"},
                        {"value": "EMPREGADO (CLT)"},
                        {"value": "8"},
                        {"value": "EMPREGADOS"},
                        {"value": "1"},
                        {"value": "E"},
                        {"value": "Engenheiro"},
                        {"value": "Engenheiro"},
                        {"value": "8033"},
                        {"value": "8033"},
                        {"value": ""},
                        {"value": "CLT"},
                        {"value": "5300"},
                        {"value": "5300"},
                        {"value": "01"},
                        {"value": "02"},
                        {"value": ""},
                        {"value": "22/05/1976"},
                        {"value": ""},
                        {"value": "RUA"},
                        {"value": "ANTONIO DUARTE DA CONCEICAO"},
                        {"value": "55"},
                        {"value": "CASA 37"},
                        {"value": "13091-241"},
                        {"value": "PQ. ANHUMAS"},
                        {"value": "CAMPINAS"},
                        {"value": "SP"},
                        {"value": ""},
                        {"value": ""},
                        {"value": "19"},
                        {"value": "991497681"},
                        {"value": "3206.0539"},
                        {"value": "00612239"},
                        {"value": "9"},
                        {"value": ""},
                        {"value": ""},
                        {"value": ""},
                        {"value": ""},
                        {"value": ""},
                        {"value": "Admin"},
                        {"value": "Nenhum"},
                        {"value": "N"},
                        {"value": "Ensino superior completo"},
                    ]
                },
                {
                    "recNo": 1,
                    "record": [
                        {"value": "123345"},
                        {"value": "00012345"},
                        {"value": "S"},
                        {"value": "Maria"},
                        {"value": "Maria Silva Sousa"},
                        {"value": "(19)987776655"},
                        {"value": "10/03/1980"},
                        {"value": "0"},
                        {"value": "10"},
                        {"value": "Brasileira"},
                        {"value": "1"},
                        {"value": "Feminino"},
                        {"value": ""},
                        {"value": "msilva"},
                        {"value": "msilva"},
                        {"value": "maria.silva@teste.com"},
                        {"value": "123.456.789-00"},
                        {"value": "11987654321"},
                        {"value": "123456"},
                        {"value": "SSP"},
                        {"value": "SP"},
                        {"value": "15/08/2000"},
                        {"value": "3270"},
                        {"value": "3536"},
                        {"value": "001.000.031.001.000.000.001"},
                        {"value": "51401"},
                        {"value": "EM ATIVIDADE NORMAL"},
                        {"value": "1"},
                        {"value": "EMPREGADO (CLT)"},
                        {"value": "8"},
                        {"value": "EMPREGADOS"},
                        {"value": "1"},
                        {"value": "E"},
                        {"value": "Engenheira"},
                        {"value": "Engenheira"},
                        {"value": "8033"},
                        {"value": "8033"},
                        {"value": ""},
                        {"value": "CLT"},
                        {"value": "5300"},
                        {"value": "5300"},
                        {"value": "04"},
                        {"value": "Baia 60"},
                        {"value": ""},
                        {"value": "22/07/1985"},
                        {"value": ""},
                        {"value": "RUA"},
                        {"value": "JOÃO PEREIRA DA SILVA"},
                        {"value": "100"},
                        {"value": "APTO 102"},
                        {"value": "04012-345"},
                        {"value": "VILA MARIANA"},
                        {"value": "SÃO PAULO"},
                        {"value": "SP"},
                        {"value": ""},
                        {"value": ""},
                        {"value": "11"},
                        {"value": "999876543"},
                        {"value": "3206.1234"},
                        {"value": "00789123"},
                        {"value": "9"},
                        {"value": ""},
                        {"value": ""},
                        {"value": ""},
                        {"value": ""},
                        {"value": ""},
                        {"value": "Adm"},
                        {"value": "Nenhum"},
                        {"value": "N"},
                        {"value": "Ensino superior completo"},
                    ]
                }
            ]
        } 
    }

    return jsonify(response)

if __name__ == '__main__':
    app.run(debug=True)